#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)


#feh --bg-scale /home/kaspar/Pictures/space.jpg
#feh --bg-center /home/kaspar/Pictures/newyork.jpg
#feh --bg-center /home/kaspar/Pictures/Old_Typewritter.jpg
#feh --bg-center /home/kaspar/Pictures/patterns.jpg
#feh --bg-scale /home/kaspar/Pictures/rubberbands.jpg
#feh --bg-scale /home/kaspar/Pictures/husky_sleeping.jpg
#feh --bg-center /home/kaspar/Pictures/micro_ant.jpg
#feh --bg-scale /home/kaspar/Pictures/gulls.jpg
#feh --bg-scale /home/kaspar/Pictures/calvin_snow_zombie.jpg
feh --bg-center /home/kaspar/Pictures/proton.jpg
xsetroot -cursor_name left_ptr
xmonad
